apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springapp-home
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/smandalbgp-sketch/springapp-home.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: springapp-home

  syncPolicy:
    automated:
      prune: true       # remove resources deleted from git
      selfHeal: true     # revert manual cluster changes back to match git
    syncOptions:
      - CreateNamespace=true
